#!/bin/bash

cookies="/tmp/etherpad-cookie-jar"

cookie_args="-b $cookies -c $cookies"

file=${1:-"-"}

pad_id=$(curl -IL $cookie_args http://etherpad.com/ep/pad/newpad | grep Location: | grep -o '[^/]*$' | tr -dc [:alnum:] | tail -n 1)

token=$(curl $cookie_args  -F "file=@$file;filename=$file.txt" -F "padId=$pad_id" http://etherpad.com/ep/pad/impexp/import | grep -o "'[^']*')" | sed "s/'\(.*\)')/\1/" | tr -dc [:alnum:])

curl $cookie_args "http://etherpad.com/ep/pad/impexp/import2?padId=$pad_id&token=$token" 

echo
echo http://etherpad.com/$pad_id
echo http://etherpad.com/$pad_id | xclip -i


